Segmenting-DMD
PaulTalbot-INL/raven pull request #8
Opened 2019-08-27 15:52 UTC by Jimmy-INL

Making time segmentation work for DMD.

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Rime segmentation only worked for ARMA, this is an attempt to generalize it to other time-dependent surrogate models.

##### What are the significant changes in functionality due to this change request?
User build a sequence of DMD surrogates based on a user-selection of number of divisions or length(s) of divisions.
##### TODO:
1. allow user to input different DMD specs for each segment, such as different ranks, modes, and/or optimized modes selection.
2. It will be great of the algorithm is extended to be smart enough to determine the time windows to fit the best number of segments and size of segments which can be learned from temporal bahavious as a function of the sampled input parameters.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2019-08-27 16:16 UTC, JiaZhou-PU reviewed
Looks great

2019-08-27 16:16 UTC, JiaZhou-PU commented on framework/SupervisedLearning/ROMCollection.py
>        # renormalize the pivot if requested, e.g. by shifting values
I am not sure about the data type in here, it looks like a list before but array now? I am fine with array though.

2019-08-27 16:16 UTC, JiaZhou-PU commented on framework/SupervisedLearning/SupervisedLearning.py
> -        return(False, ' The array must be 1-d. Got shape: '+str(np.asarray(arrayIn).shape))
Why removing this check?

2019-08-27 16:28 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/ROMCollection.py
>        # renormalize the pivot if requested, e.g. by shifting values
I think the `TODO` is resolved by this change, probably, so we can remove the `TODO` and leave the rest of the comment.

2019-08-27 16:29 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> -        return(False, ' The array must be 1-d. Got shape: '+str(np.asarray(arrayIn).shape))
I agree; how did this pass for DMD before this PR? Was it only ever trained on single histories?

2019-08-27 16:40 UTC, PaulTalbot-INL requested changes
A few things to spruce up. I realize most of the problems were inherited from older implementation, but I want to leave this so the next person doesn't have to struggle to make sense of it, at least not as much as before.

2019-08-27 16:40 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/DynamicModeDecomposition.py
> +    if self.amITrained:
Please add a comment about why this "if" was added. It's generally not okay to deepcopy an untrained SVL engine ... except we do it in the ROMCollection, so that's the exception. That comment might save someone a lot of searching someday.

2019-08-27 16:40 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/ROMCollection.py
> +        if len(value)>1:
Is there every a check in `Clustered` that disables the ability to specify different lengths? I believe it calls this same `subdivideDomain` method, but without that check this would get messy fast without a good error.

2019-08-27 16:40 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> +    featureValues = np.zeros(shape=(np.shape(targetValues)[0],len(self.features)))
Is this right? It looks like the argument to `np.zeros` might look like
```python
  np.zeros( [(2,3), 4] )
```
(square brackets for clarity, it's actually all tuples). Is zeros okay with mixed tuples? Either way, this could probably be clearer.

2019-08-27 16:40 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> +        if np.shape(valueToUse)[0] != featureValues[:,0].size:
This seems odd to me. What is the indexing or shape of valueToUse versus featureValues? At minimum there should be more comments here to explain this check.

2019-08-27 19:21 UTC, Jimmy-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> -        return(False, ' The array must be 1-d. Got shape: '+str(np.asarray(arrayIn).shape))
It did not. It always gave me an error here. the array is always bigger than 1-d

2019-08-27 19:35 UTC, Jimmy-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> +        if np.shape(valueToUse)[0] != featureValues[:,0].size:
This change changes nothing, but I prefer to use shape with ndarrays than len. In Arma, the first dimension is always 1, but in other t-dependent surroagates this will be the number of samples. I will probably add a comment though.

2019-09-03 14:53 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/DynamicModeDecomposition.py
> +    if self.amITrained:
👍

2019-09-03 14:53 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/ROMCollection.py
>        # renormalize the pivot if requested, e.g. by shifting values
👍

2019-09-03 14:54 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> -        return(False, ' The array must be 1-d. Got shape: '+str(np.asarray(arrayIn).shape))
👍 
Note we have to revisit this if/when we start training ROMs on ND input data; for now this is not a thing.

2019-09-03 14:54 UTC, PaulTalbot-INL commented on framework/SupervisedLearning/SupervisedLearning.py
> +        if np.shape(valueToUse)[0] != featureValues[:,0].size:
👍

2019-09-03 14:57 UTC, PaulTalbot-INL approved these changes
Looks good to me. Since this all has to be reviewed before merging into devel, this stage of contribution is fine for now.

2019-09-03 15:00 UTC, PaulTalbot-INL commented
I'll hold off merging this for now until a test case can be added.

2020-02-10 18:16 UTC, PaulTalbot-INL commented
@Jimmy-INL Does this PR still have a purpose?

2020-02-13 03:15 UTC, Jimmy-INL commented
I think I need to rebase and then generate anew PR on devel

2021-04-08 20:55 UTC, closed without merging